// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/quotes": {
            "post": {
                "tags": [
                    "Cotações"
                ],
                "summary": "Cotação de Frete",
                "parameters": [
                    {
                        "description": "Payload com as informações necessárias para realizar a cotação de frete",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.RequestQuote"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Resposta com sucesso",
                        "schema": {
                            "$ref": "#/definitions/domain.Quote"
                        }
                    },
                    "400": {
                        "description": "Erro de requisição inválida",
                        "schema": {
                            "$ref": "#/definitions/v1.errorResponse"
                        }
                    }
                }
            }
        },
        "/v1/quotes/metrics": {
            "get": {
                "description": "Retorna um resumo das cotações, podendo limitar pelo número de últimas cotações",
                "tags": [
                    "Cotações"
                ],
                "summary": "Resumo Cotação de Frete",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Número de últimas cotações a serem retornadas",
                        "name": "last_quotes",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de cotações",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Quote"
                            }
                        }
                    },
                    "400": {
                        "description": "Erro de requisição inválida",
                        "schema": {
                            "$ref": "#/definitions/v1.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.CarrierInfo": {
            "type": "object",
            "properties": {
                "company_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "reference": {
                    "type": "integer"
                },
                "registered_number": {
                    "type": "string"
                },
                "state_inscription": {
                    "type": "string"
                }
            }
        },
        "domain.DeliveryTimeInfo": {
            "type": "object",
            "properties": {
                "days": {
                    "type": "integer"
                },
                "estimated_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "domain.Dispatcher": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "offers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Offer"
                    }
                },
                "registered_number_dispatcher": {
                    "type": "string"
                },
                "registered_number_shipper": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "zipcode_origin": {
                    "type": "integer"
                }
            }
        },
        "domain.Offer": {
            "type": "object",
            "properties": {
                "carrier": {
                    "$ref": "#/definitions/domain.CarrierInfo"
                },
                "carrier_original_delivery_time": {
                    "$ref": "#/definitions/domain.DeliveryTimeInfo"
                },
                "cost_price": {
                    "type": "number"
                },
                "delivery_time": {
                    "$ref": "#/definitions/domain.DeliveryTimeInfo"
                },
                "expiration": {
                    "type": "string"
                },
                "final_price": {
                    "type": "number"
                },
                "home_delivery": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "identifier": {
                    "type": "string"
                },
                "modal": {
                    "type": "string"
                },
                "offer": {
                    "type": "integer"
                },
                "original_delivery_time": {
                    "$ref": "#/definitions/domain.DeliveryTimeInfo"
                },
                "service": {
                    "type": "string"
                },
                "service_code": {
                    "type": "string"
                },
                "simulation_type": {
                    "type": "integer"
                },
                "weights": {
                    "$ref": "#/definitions/domain.WeightInfo"
                }
            }
        },
        "domain.Quote": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "dispatchers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Dispatcher"
                    }
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "domain.WeightInfo": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "real": {
                    "type": "integer"
                }
            }
        },
        "requests.RequestQuote": {
            "type": "object",
            "required": [
                "recipient",
                "volumes"
            ],
            "properties": {
                "recipient": {
                    "type": "object",
                    "required": [
                        "address"
                    ],
                    "properties": {
                        "address": {
                            "description": "dive valida campos internos",
                            "type": "object",
                            "required": [
                                "zipcode"
                            ],
                            "properties": {
                                "zipcode": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                },
                "volumes": {
                    "description": "dive percorre slice",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": [
                            "amount",
                            "category",
                            "height",
                            "length",
                            "price",
                            "sku",
                            "unitary_weight",
                            "width"
                        ],
                        "properties": {
                            "amount": {
                                "type": "integer"
                            },
                            "category": {
                                "type": "integer"
                            },
                            "height": {
                                "type": "number"
                            },
                            "length": {
                                "type": "number"
                            },
                            "price": {
                                "type": "integer"
                            },
                            "sku": {
                                "type": "string"
                            },
                            "unitary_weight": {
                                "type": "integer"
                            },
                            "width": {
                                "type": "number"
                            }
                        }
                    }
                }
            }
        },
        "v1.errorResponse": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
